---
abstract: 'build full-screen console-style applications'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Identity: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Console
provides:
  Tickit::Console:
    file: lib/Tickit/Console.pm
    version: 0.04
  Tickit::Console::Tab:
    file: lib/Tickit/Console.pm
requires:
  Tickit: 0
  Tickit::Widget::Entry: 0
  Tickit::Widget::Scroller: 0.04
  Tickit::Widget::Tabbed: 0.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
